---
name: devdocs
version: "0.1.12"
cog_bundle_version: 3
docker:
  image: pauldub/cog-devdocs
  tag: latest
permissions:
  - devdocs:read
commands:
  doc:
    executable: /home/bundle/cog-command
    description: Lookup documentation on devdocs.io
    documentation: "doc <subject> <query> - Search documentation on devdocs.io"
    rules:
    - "must have devdocs:read"
